### ISSUE TITLE
Authentication, HTTPS,  and Swagger generation.

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/perceptor#105]
Thanks to Matt we have a swagger spec -- I tried generating an api client w / swagger, but couldn't use it.  However, it made a lot of stubs that look very close to what we have in the api/ packages , so it's a very possible step to flesh this workout and kill api / to be replaced entirely w/ swagger auto generated stuff.

1) Swagger go might be fragile, but here's what I did, seemed to work:
```
swagger generate client -h -f core-rest-api.swagger --target ${GOPATH}/src/github.com/blackducksoftware/perceptor/pkg/api/
```

Created a models/ and a client/ directory.
It also created a dependencies/ binary.

```
pkg/api/client
├── perceiver
│   ├── add_pod_parameters.go
│   ├── add_pod_responses.go
│   ├── all_pods_parameters.go
│   ├── all_pods_responses.go
│   ├── delete_pod_parameters.go
│   ├── delete_pod_responses.go
│   ├── get_scan_results_parameters.go
│   ├── get_scan_results_responses.go
│   ├── perceiver_client.go
│   ├── update_pod_parameters.go
│   └── update_pod_responses.go
├── perceptor_core_client.go
└── scanner
    ├── finished_scan_parameters.go
    ├── finished_scan_responses.go
    ├── get_next_image_parameters.go
    ├── get_next_image_responses.go
    └── scanner_client.go
```

2) NOTE Our core model doesn't use pointers, also the core model seems to try to decouple from the api model, not sure why yet...  , swagger heavily overuses them it seems (i.e. even for strings), 
Anyways, just wanted to brain dump in case anyone else is playing with this.

**Comment by mattfenwick** [comment]
Closing in favor of #114
