### ISSUE TITLE
Rethink our Swagger docs

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/perceptor#114]
@jasonf1234 is doing some  really cool swagger stuff for reverse engineering swagger docs from golang objects. Lets sketch out the actual goals in this issue if we're planning on merging this upstream... API maintenance will possibly require building some bots in the long term, and also, probably we'll want to publish a home for the java API objects as well.

**Comment by jayunit100** [comment]
- bots for pushing apis 
- tests for non golang api clients 
- should we gate commits on API manual updates (like they do in kube upstream) ?

**Comment by rrati** [comment]
IMO we should definitely gate commits on API issues.  If the api changes and the swagger isn't updated, that's a problem.

**Comment by jayunit100** [comment]
Plan going forward:

- update the PR w/ a real swagger spec.
- update the PR w/ a README outlinging API policy changes.

**Comment by jasonf1234** [comment]
### Problem Statement
The current issue is that the swagger spec currently in GitHub is out-of-date with the actual perceptor REST API. This makes it difficult for anybody who wants to build a perceiver as they have to look at the perceptor code (in pkg/api) to determine the current REST API. Also, if a developer wishes to generate a language-specific client SDK based on the current swagger spec, the output will not work against the current perceptor.

### Proposed Solution
In the short-term we want to accomplish the following:
* Generate a swagger spec that is up-to-date with the current perceptor REST API
* Outline a manual process in the README for generating a new swagger spec in response to future REST API changes

To accomplish the short-term goals the plan is to (as @jayunit100 stated above):
* update the PR w/ a real swagger spec.
* update the PR w/ a README outlining API policy changes

Developers can manually generate language-specific client SDKs against the swagger spec. 

### Future Work
We would like to get to a point where the swagger spec was the "single source of truth" for **both** the server as well as client SDKs. In this scenario: 
* Any updates to the REST API or model definitions would occur in the swagger spec **first** 
* The current code annotations would become moot as the spec would be the focal point for API and model changes 

From that swagger spec, new server stubs would be generated and business logic written against those new stubs. Client SDKs could also be produced which would be up-to-date.

**Comment by mattfenwick** [comment]
Fixed by #113
