### ISSUE TITLE
Pods have violation-related annotations before scans complete

### ISSUE THREAD

**Issue by jlin963** [blackducksoftware/perceptor#121]
https://github.com/blackducksoftware/perceivers/issues/45

Opening in perceptor per Matt's request after more investigation.

**Comment by jlin963** [comment]
fyi this is also happening on OpenShift Enterprise + downstream

Server https://ec2-18-219-130-237.us-east-2.compute.amazonaws.com:8443
openshift v3.6.173.0.96
kubernetes v1.6.1+5115d708d7

**Comment by mattfenwick** [comment]
I wonder if this is happening because of something related to [this issue](https://github.com/blackducksoftware/perceivers/issues/44) -- perceptor sees a pod come in with 0 containers, thinks it's already done.

**Comment by mattfenwick** [comment]
Fixed by https://github.com/blackducksoftware/perceivers/pull/53.
