### ISSUE TITLE
"java scanner failed for image" error in perceptor-scanner (exit status 74 in perceptor)

### ISSUE THREAD

**Issue by jlin963** [blackducksoftware/perceptor#129]
[perceptor-scanner-ndj1t.log](https://github.com/blackducksoftware/perceptor/files/1880996/perceptor-scanner-ndj1t.log)
[perceptor-scanner-vq0lk.log](https://github.com/blackducksoftware/perceptor/files/1880997/perceptor-scanner-vq0lk.log)
[perceptor-1dhhw.log](https://github.com/blackducksoftware/perceptor/files/1880998/perceptor-1dhhw.log)

perceptor-scanner error e.g.:

> time="2018-04-04T18:04:36Z" level=error msg="java scanner failed for image e6e705dddc33c614beffab68594ea83fd56e0761c7eae5ddab4038968ebcc748 with error exit status 74 and output:\n INFO: Start wrapper: ScanCliWrapperSettings [commandLine=org.apache.commons.cli.CommandLine@5ce65a89, fileUriSet=null, scheme=https, host=18.188.116.2.xip.io, port=443, username=none, password=<NOT SHOWN>]...\nDEBUG: Cached implementation found.  Validating checksums\n WARN: The current scan implementation does not match the version found on the host '18.188.116.2.xip.io:443', however an explicit request was made to skip the update. THIS MAY RESULT IN INCOMPATIBLE SCANS.\nDEBUG: have class c: com.simontuffs.onejar.Boot\nDEBUG: have main method m: public static void com.simontuffs.onejar.Boot.main(java.lang.String[]) throws java.lang.Exception\nDEBUG: resolveRoot File(arg:/var/images/registry.access.redhat.com_jboss-eap-6_eap64-openshift@sha256:e6e705dddc33c614beffab68594ea83fd56e0761c7eae5ddab4038968ebcc748.tar)... \n INFO: Start scan loop: ScanClientSettings [commandLine=org.apache.commons.cli.CommandLine@553f17c, fileUriSet=[file://perceptor-scanner-jd31q/var/images/registry.access.redhat.com_jboss-eap-6_eap64-openshift@sha256:e6e705dddc33c614beffab68594ea83fd56e0761c7eae5ddab4038968ebcc748.tar], dryRunWriteDir=No dry run file., dryRunReadFile=No dry run file., snippetMatching=false, snippetMatchingOnly=false, fullSnippetScan=false, logDir=Unspecified Value, scheme=https, host=18.188.116.2.xip.io, port=443, name=Optional[e6e705dddc33c614beffab68594ea83fd56e0761c7eae5ddab4038968ebcc748], project=Optional[registry.access.redhat.com/jboss-eap-6/eap64-openshift-e6e705dddc33c614beffab68594ea83fd56e0761c7eae5ddab4038968ebcc748], release=Optional[e6e705dddc33c614beffab68594ea83fd56e0761c7eae5ddab4038968ebcc748], username=sysadmin, password=<NOT SHOWN>]...\n INFO: Initialize client for 18.188.116.2.xip.io:443\n INFO: RestResourceClient created. SingleRelativePath = {scanId}, URI = https://18.188.116.2.xip.io:443/api/v1/scans \n INFO: RestReso

perceptor error e.g.:

> time="2018-04-05T16:31:40Z" level=error msg="error running scan client -- exit status 74"

Setup:
-OpenShift Enterprise cluster
-downstream code (using opssight-connector)

**Comment by jlin963** [comment]
I am also starting to see exit code 68 as of time="2018-04-05T07:44:35Z"

> time="2018-04-05T07:44:35Z" level=error msg="error running scan client -- exit status 68"

**Comment by mattfenwick** [comment]
Looks like this is a Hub issue.
