### ISSUE TITLE
Some images are being scanned twice?

### ISSUE THREAD

**Issue by jlin963** [blackducksoftware/perceptor#130]
Setup:
-OpenShift Enterprise cluster
-downstream code (using opssight-connector)

I'm seeing two scans in the scan history in the Hub for some of the images (both completed). 
<img width="1051" alt="screen shot 2018-04-05 at 1 53 12 pm" src="https://user-images.githubusercontent.com/31659508/38382733-b76473ca-38d8-11e8-80e5-804d33c25d54.png">

Also seeing this error in in perceptor logs:

> time="2018-04-05T13:21:53Z" level=error msg="unable to fetch updated scan results for sha 0ec9f42efa1102bd0a8e5a96847c1d9788afd774381c38a742c6b0d1628ff5b3: expected to find one scan summary for code location 0ec9f42efa1102bd0a8e5a96847c1d9788afd774381c38a742c6b0d1628ff5b3, found 2"

[perceptor-1dhhw (1).log](https://github.com/blackducksoftware/perceptor/files/1881158/perceptor-1dhhw.1.log)

**Comment by mattfenwick** [comment]
This is probably due to perceptor<->hub connectivity issues.

**Comment by mattfenwick** [comment]
Fixed by #136
