### ISSUE TITLE
hub connectivity issues

### ISSUE THREAD

**Issue by mattfenwick** [blackducksoftware/perceptor#134]
1. unable to talk to hub: image may get scanned multiple times
2. image scanned multiple times: perceptor refuses to treat it as scanned upon startup and initial hub check

**Comment by jayunit100** [comment]
Fix: 

1) quick workaround for our 1x perceptor release = is to continue *anyway*
2) MattF to implement an actual metric for this, so when the hub has more then one scan result, we can count how often it happened and have a smarter solution (i.e. pick the latest, use hub API to delete that scan)

**Comment by mattfenwick** [comment]
2 is done -- see #136

**Comment by mattfenwick** [comment]
#1 is done as well
