### ISSUE TITLE
Use the hub client timeout in seconds from Viper config

### ISSUE THREAD

**Issue by msenmurugan** [blackducksoftware/perceptor#138]
Currently the Perceptor config map is created with Hub client timeout. The Perceptor code need to be modified to use the Hub client timeout from Viper config instead of hard code values.

**Comment by jayunit100** [comment]
To avoid bikeshed: let’s give the hub either 30s or preferred 120seconds hub client api timeouts and move on.  And then file a follow up bc it could take a long time to sort out the “right answer”, and the answer will be obsoleted soon probably
 with the changing containerization and scalability boundaries that we are getting from hub improvements.

**Comment by mattfenwick** [comment]
Done in #139
