### ISSUE TITLE
Check how often Perceptor state refreshes

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/perceptor#180]
We saw a 'frozen' perceptor state recently...  *(update , it eventually gets back to the right state, but it took a second wave of updating to do so - see below)*

![screen shot 2018-06-27 at 11 01 03 am](https://user-images.githubusercontent.com/826111/41982487-877a8d4a-79f9-11e8-9789-08f7fd676ead.png)

I deleted the perceptor pod to see if it would correctly get the new state, it did, but the question now is ~ will it ever recover / how often does it get updates about pods that have left the cluster ? 

The discrepancy between restarts here indicates that something, somewhere, is stale.

**Comment by jayunit100** [comment]
Interestingly, it gets back to normal state after a second wave.  Not sure why.  

![screen shot 2018-06-27 at 11 05 26 am](https://user-images.githubusercontent.com/826111/41982673-03a04a7c-79fa-11e8-9918-8373dc8b3440.png)

**Comment by mattfenwick** [comment]
Check out the metrics:

```
perceptor_core_http_handled_status_codes{path="allpods"}
```

<img width="1646" alt="screen shot 2018-06-27 at 11 14 18 am" src="https://user-images.githubusercontent.com/952655/41983161-4419210e-79fb-11e8-9ee0-f983ecc22fff.png">

There was a perceiver dump for the second spike.

This is expected behavior.
