### ISSUE TITLE
Default service account can't read pods or enumerate all the things in OpenShift 3.7

### ISSUE THREAD

**Issue by sheppduck** [blackducksoftware/perceptor#53]
Brand new OCP 3.7 4 node cluster, many apps installed and running, including the perceptor - unfortunately as soon as the perceptor tried to enumerate PODs and images we see:

time="2018-02-16T21:22:02Z" level=info msg="starting pod-perceiver"
--
  | time="2018-02-16T21:22:02Z" level=info msg="starting pod controllers"
  | E0216 21:22:02.421656       1 reflector.go:205] github.com/blackducksoftware/perceivers/pod/pkg/controller/pod_controller.go:103: Failed to list *v1.Pod: User "system:serviceaccount:bds-perceptor:openshift-perceiver" cannot list pods at the cluster scope: User "system:serviceaccount:bds-perceptor:openshift-perceiver" cannot list all pods in the cluster (get pods)
  | E0216 21:22:03.424139       1 reflector.go:205] github.com/blackducksoftware/perceivers/pod/pkg/controller/pod_controller.go:103: Failed to list *v1.Pod: User "system:serviceaccount:bds-perceptor:openshift-perceiver" cannot list pods at the cluster scope: User "system:serviceaccount:bds-perceptor:openshift-perceiver" cannot list all pods in the cluster (get pods)
  | E0216 21:22:04.425714       1 reflector.go:205] github.com/blackducksoftware/perceivers/pod/pkg/controller/pod_controller.go:103: Failed to list *v1.Pod: User "system:serviceaccount:bds-perceptor:openshift-perceiver" cannot list pods at the cluster scope: User "system:serviceaccount:bds-perceptor:openshift-perceiver" cannot list all pods in the cluster (get pods)
  | E0216 21:22:05.427277       1 reflector.go:205]

over and over
Nothing discovered, nothing scanned
this is with @msenmurugan newest openshift install.  He says it works fine on openshift ORIGIN 3.6, not OCP...

**Comment by mattfenwick** [comment]
@msenmurugan @sheppduck this should be fixed by the new installer; can you verify, and if it's still broken, file an issue either on the perceptor-protoform or perceivers repo?
