### ISSUE TITLE
Image spec

### ISSUE THREAD

**Issue by mattfenwick** [blackducksoftware/perceptor#61]
```
{
  # Name is <registry>/<user>/<project>
  "Name": "docker.io/blackducksoftware/hub-registration",

  "Sha": "cb4983d8399a59bb5ee6e68b6177d878966a8fe41abe18a45c3b1d8809f1d043",

  # DockerImage is what the Kubernetes API says the container image string is -- it's ambiguous, but human readable
  "DockerImage": "blackducksoftware/hub-registration:4.4.0"
}
```

Sources:
 - Name and Sha are from splitting a kubernetes `pod.Status.ContainerStatuses[0].ImageID` string
 - DockerImage is from a kubernetes `pod.Status.ContainerStatuses[0].Image` string.

**Comment by mattfenwick** [comment]
Possible desired format for future use (depending on how hard it is to parse docker image strings):

```
{
  "Registry": "docker.io",
  "User": "blackducksoftware",
  "Project": "hub-registration",
  "Tag": "4.4.0",
  "Sha": "cb4983d8399a59bb5ee6e68b6177d878966a8fe41abe18a45c3b1d8809f1d043"
}
```

**Comment by mattfenwick** [comment]
This might be a better fit:

```
{
  "Repository": "docker.io",
  "NameComponents": ["blackducksoftware", "hub-registration"],
  "Tag": "4.4.0",
  "Sha": "cb4983d8399a59bb5ee6e68b6177d878966a8fe41abe18a45c3b1d8809f1d043"
}
```

See https://stackoverflow.com/questions/37861791/how-are-docker-image-names-parsed?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa .

**Comment by rrati** [comment]
Proposed spec:
{
  "Repository": "<hostname>:<port>:<path components",
  "Tag": "1.1.1",
  "Sha: "<sha<",
}

Tag would be optional

**Comment by mattfenwick** [comment]
Sources:

 - [this stackoverflow question](https://stackoverflow.com/questions/37861791/how-are-docker-image-names-parsed?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)
 - [the Docker spec](https://github.com/moby/moby/blob/master/image/spec/v1.2.md#terminology).

**Comment by mattfenwick** [comment]
[This will require a change to the scanner as well](https://github.com/blackducksoftware/perceptor-scanner/issues/72).

**Comment by mattfenwick** [comment]
Done -- see #190 ; https://github.com/blackducksoftware/perceptor-scanner/issues/72.
