### ISSUE TITLE
inject docker username, password into perceptor-scanner as part of openshift install

### ISSUE THREAD

**Issue by mattfenwick** [blackducksoftware/perceptor#65]
This will allow the scanner to pull images from the local openshift registry.

**Comment by rrati** [comment]
Can this be done with service account tokens or something local to openshift?  I'd prefer we not inject username/passwords into yaml files for something we have no control over (openshift registry)

**Comment by mattfenwick** [comment]
The alternative could look something like this:

> The scanner has a service account.  I assume it's not enough to just give that service account the required creds, so maybe there is a way to get the creds for the service account and pass that.  We do something similar in the ose-scanner 1.x installer
> It accesses the registry directly vs through the service endpoint, but the trick of passing the creds should work if we can get the creds programmatically
